### PR TITLE
Fixed input build and Exception if less than 2 files to concatenate

### PR DESCRIPTION
**Pull request by alex6dj**

### CODE REVIEW

**Comment by alex6dj** [comment]
Hmmm, unrelated exception...

**Comment by alex6dj** [comment]
The problem seems to be related to
`Assert.True(resetEvent.WaitOne(2000));` on line 68 at ConversionQueueTests.cs
Maybe an overloaded server did not run the test in the required time.

**Comment by alex6dj** [comment]
The test fails because a video file that does not contain audio is used in this, and the Concatenate method expects everyone to have audio ...

**Comment by tomaszzmuda** [comment]
I'll merge it into concat_filter branch and fix bug when one file doesn't have audio stream.
Unit tests MUST work before pushed to master.

**Pull request merged**
