### PR TITLE
Set max bitrate

### PR DESCRIPTION
**Pull request by tomaszzmuda**

### CODE REVIEW

**Review by delphianaus — COMMENTED** [review]
Why do you have setbitrate in audiostream ? the -b:V is only for video streams ?

**Comment by tomaszzmuda** [comment]
image
Bitrate can be set to AudioStream too.
It's -b:**a** not -b:**v**

**Comment by delphianaus** [comment]
Change it to -b:a and i will mark it as done.

**Review by delphianaus — APPROVED** [review]
All good.

**Comment by delphianaus** [comment]
Hey i discovered a few issues


AudioStream.CopyStream

It does this

_audioFilters["-c:v copy"] = string.Empty;

it should set the codec to Copy and in BuildAudioCodec it should set the
output as -c:a copy. not to mention the changes dont show up in
buildaudiocodec for vorbis mp2 and wavepack extended params.

Also on the latest copy of ffmpeg if you use nvidia hardware acceleration (
NVENC) and set the preset to fast it fails ( maybe shouldnt allow preset to
be set if you use hw accel ? )

Kind Regards

Justin

**Comment by tomaszzmuda** [comment]
Hey,

I pushed changes with AudioStream.CopyStream #313 

There are a lot of cases when FFmpeg fails. There is no possibility to implement all cases so I rely on users knowledge and tests :)

**Pull request merged**
